FROM openjdk:17-alpine
RUN apk --no-cache add curl

ARG WORK_DIR=/opt/config-service
ARG ARTIFACT_NAME=supremeshop-config-svc.jar
ARG APP_PORT=5016

ENV FINAL_ARTIFACT=${ARTIFACT_NAME}

RUN mkdir ${WORK_DIR}

WORKDIR ${WORK_DIR}

COPY target/${ARTIFACT_NAME} ${WORK_DIR}

EXPOSE ${APP_PORT}

CMD [ "sh","-c", "java -jar ${FINAL_ARTIFACT}"]
