spring:
#  application:
#    name: ${APP_NAME:supremeshop-category-service}
  datasource:
    username: '${CATEGORIES_DB_USER:admin}'
    password: '${CATEGORIES_DB_PASSWORD:password}'
    url: 'jdbc:${CATEGORIES_DB_TYPE:mysql}://${CATEGOIRIES_DB_HOST:supreemdb.cc4iqoikkjsk.ap-south-1.rds.amazonaws.com}:${CATEGORIES_DB_PORT:3306}/${CATEGORIES_DB_SCHEMA:category_service}'
  jpa:
    hibernate:
      ddl-auto: '${CATEGORIES_DB_DDL_AUTO:update}'
    show-sql: true



  data:
    redis:
      host: ${REDIS_SERVER_HOST:cache.supremeshope.com}
      port: ${REDIS_SERVER_PORT:80}
      password: ${REDIS_SERVER_PASSWORD:Redis123$}

server:
  port: ${APP_PORT:5016}


eureka:
  client:
    serviceUrl:
      defaultZone: http://supremeshop-registry-svc:8761/eureka/


axon:
  axonserver:
    servers: ${AXON_SERVER_HOST:localhost}:${AXON_SERVER_PORT:8024}

#api:
#  gateway:
#    path: http://${GATEWAY_SVC_HOST:localhost}:${GATEWAY__SVC_PORT:5012}

logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%X{traceId:-},%X{spanId:-}] ${LOG_LEVEL_PATTERN:-%5p} %m%n"

management:
  tracing:
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: http://zipkin:9411/api/v2/spans
springdoc:
  packagesToScan: com.supremeshop.platform.category