spring:
  #  application:
  #    name: ${APP_NAME:supremeshop-brands-service}
  output:
    ansi:
      enabled: always
  data:
    mongodb:
      uri: ${MONGO_DB_URI:mongodb+srv://supremeshop-mongoDB:supremeshop%402023@cluster0.dknmv5d.mongodb.net/brand_service?retryWrites=true&w=majority}
      auto-index-creation: ${MONGO_AUTO_INDEX_CREATION:true}
    redis:
      host: '${REDIS_SERVER_HOST:cache.supremeshope.com}'
      port: '${REDIS_SERVER_PORT:80}'
      password: '${REDIS_SERVER_PASSWORD:Redis123$}'

server:
  port: ${APP_PORT:5017}

  cloud:
    loadbalancer:
      enabled: true

services:
  categories:
    ##base-uri: '${CATEGORIES_BASE_URI:http://localhost:5016/categories}'
    base-uri: http://${CATEGORIES_SVC_HOST:localhost}:${CATEGORIES_SVC_PORT:5016}


axon:
  axonserver:
    servers: ${AXON_SERVER_HOST:localhost}:${AXON_SERVER_PORT:8024}
eureka:
  client:
    serviceUrl:
      defaultZone: http://${SERVICE_REGISTRY_HOST:localhost}:${SERVICE_REGISTRY_PORT:8761}/eureka/
  instance:
    hostname: ${SERVICE_REGISTRY_HOST:localhost}
    preferIpAddress: true

#api:
#  gateway:
#    path: http://${GATEWAY_SVC_HOST:localhost}:${GATEWAY_SVC_PORT:5012}

logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%X{traceId:-},%X{spanId:-}] ${LOG_LEVEL_PATTERN:-%5p} %m%n"

management:
  tracing:
    sampling:
      probability: 1.0

springdoc:
  packagesToScan: com.supremeshop.platform.brand