spring:
#  application:
#    name: ${APP_NAME:supremeshop-category-service}
  datasource:
    username: admin
    password: password
    url: jdbc:${CATEGORIES_DB_TYPE:mysql}://${CATEGOIRIES_DB_HOST:supreemdb.cc4iqoikkjsk.ap-south-1.rds.amazonaws.com}:${CATEGORIES_DB_PORT:3306}/${CATEGORIES_DB_SCHEMA:category_service}
    driver-class-name: com.mysql.cj.jdbc.Driver
    hibernate:
      ddl-auto: update
    show-sql: true

  jpa:
    database-platform: org.hibernate.dialect.MySQL5Dialect

  data:
    redis:
      host: ${REDIS_SERVER_HOST:cache.supremeshope.com}
      port: ${REDIS_SERVER_PORT:80}
      password: ${REDIS_SERVER_PASSWORD:Redis123$}

server:
  port: ${APP_PORT:5016}


eureka:
  client:
    service-url:
      defaultZone: http://${SERVICE_REGISTRY_HOST:localhost}:${SERVICE_REGISTRY_PORT:8761}/eureka/
  instance:
    hostname: ${SERVICE_REGISTRY_HOST:localhost}
    prefer-ip-address: true
axon:
  axonserver:
    servers: ${AXON_SERVER_HOST:localhost}:${AXON_SERVER_PORT:8024}

#api:
#  gateway:
#    path: http://${GATEWAY_SVC_HOST:localhost}:${GATEWAY__SVC_PORT:5012}

logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%X{traceId:-},%X{spanId:-}] ${LOG_LEVEL_PATTERN:-%5p} %m%n"

management:
  tracing:
    sampling:
      probability: 1.0
springdoc:
  packagesToScan: com.supremeshop.platform.category